import type { PatientData } from "@/types/patient"

export interface PatientService {
  getPatients: () => Promise<PatientData[]>
  getTotalPatients: () => Promise<number> // Added method to get total patients
}

// This is a mock service that would be replaced with real API calls
export const patientService: PatientService = {
  async getPatients() {
    return [
      {
        id: "1",
        name: "John Doe",
        email: "john@example.com",
        phone: "123-456-7890",
        dateOfBirth: "1978-01-01",
        age: 45,
        gender: "Female",
        address: "123 Main St, Anytown, USA",
        bloodType: "O+",
        allergies: ["None"],
        lastVisit: "2023-03-15",
        status: "Active",
        avatar: "/placeholder-user.jpg",
      },
      {
        id: "2",
        name: "Sarah Johnson",
        email: "sarah@example.com",
        phone: "234-567-8901",
        dateOfBirth: "1991-05-15",
        age: 32,
        gender: "Female",
        address: "456 Elm St, Anytown, USA",
        bloodType: "A-",
        allergies: ["Peanuts"],
        lastVisit: "2023-03-10",
        status: "Active",
        avatar: "/placeholder-user.jpg",
      },
      {
        id: "3",
        name: "Michael Brown",
        email: "michael@example.com",
        phone: "345-678-9012",
        dateOfBirth: "1965-09-20",
        age: 58,
        gender: "Male",
        address: "789 Oak St, Anytown, USA",
        bloodType: "B+",
        allergies: ["None"],
        lastVisit: "2023-02-28",
        status: "Inactive",
        avatar: "/placeholder-user.jpg",
      },
      {
        id: "4",
        name: "Emily Davis",
        email: "emily@example.com",
        phone: "456-789-0123",
        dateOfBirth: "1996-11-30",
        age: 27,
        gender: "Female",
        address: "321 Pine St, Anytown, USA",
        bloodType: "AB+",
        allergies: ["Dust"],
        lastVisit: "2023-03-05",
        status: "Active",
        avatar: "/placeholder-user.jpg",
      },
      {
        id: "5",
        name: "Robert Wilson",
        email: "robert@example.com",
        phone: "567-890-1234",
        dateOfBirth: "1961-07-15",
        age: 62,
        gender: "Male",
        address: "654 Maple St, Anytown, USA",
        bloodType: "O-",
        allergies: ["None"],
        lastVisit: "2023-03-12",
        status: "Active",
        avatar: "/placeholder-user.jpg",
      },
      {
        id: "6",
        name: "Alice Smith",
        email: "alice@example.com",
        phone: "678-901-2345",
        dateOfBirth: "1993-02-22",
        age: 30,
        gender: "Female",
        address: "987 Cedar St, Anytown, USA",
        bloodType: "A+",
        allergies: ["Shellfish"],
        lastVisit: "2023-03-01",
        status: "Active",
        avatar: "/placeholder-user.jpg",
      },
      {
        id: "7",
        name: "David Johnson",
        email: "david@example.com",
        phone: "789-012-3456",
        dateOfBirth: "1983-04-10",
        age: 40,
        gender: "Male",
        address: "135 Birch St, Anytown, USA",
        bloodType: "B-",
        allergies: ["None"],
        lastVisit: "2023-02-20",
        status: "Inactive",
        avatar: "/placeholder-user.jpg",
      },
      {
        id: "8",
        name: "Laura Wilson",
        email: "laura@example.com",
        phone: "890-123-4567",
        dateOfBirth: "1973-08-25",
        age: 50,
        gender: "Female",
        address: "246 Spruce St, Anytown, USA",
        bloodType: "O+",
        allergies: ["None"],
        lastVisit: "2023-03-10",
        status: "Active",
        avatar: "/placeholder-user.jpg",
      },
      {
        id: "9",
        name: "James Brown",
        email: "james@example.com",
        phone: "901-234-5678",
        dateOfBirth: "1988-12-05",
        age: 35,
        gender: "Male",
        address: "357 Fir St, Anytown, USA",
        bloodType: "AB-",
        allergies: ["None"],
        lastVisit: "2023-03-15",
        status: "Active",
        avatar: "/placeholder-user.jpg",
      },
      {
        id: "10",
        name: "Sophia Davis",
        email: "sophia@example.com",
        phone: "012-345-6789",
        dateOfBirth: "1995-06-18",
        age: 28,
        gender: "Female",
        address: "468 Willow St, Anytown, USA",
        bloodType: "A-",
        allergies: ["None"],
        lastVisit: "2023-03-12",
        status: "Inactive",
        avatar: "/placeholder-user.jpg",
      },
    ]
  },
  async getTotalPatients() {
    const patients = await this.getPatients();
    return patients.length;
  },
}
